/****************************************************************************
 ****************************************************************************
 ***
 ***   This header was automatically generated from a Linux kernel header
 ***   of the same name, to make information necessary for userspace to
 ***   call into the kernel available to libc.  It contains only constants,
 ***   structures, and macros generated from the original header, and thus,
 ***   contains no copyrightable information.
 ***
 ****************************************************************************
 ****************************************************************************/
#ifndef _ASM_X32_UNISTD_H_
#define _ASM_X32_UNISTD_H_

/* X32 system call mask.  */
#define __X32_SYSCALL_BIT	0x40000000

/* The first x32 system call.  */
#define __X32_SYSCALL_BASE	512

#define __NR_COMMON_SYSCALL(n)	(__X32_SYSCALL_BIT | (n))
#define __NR_X32_SYSCALL(n)	(__X32_SYSCALL_BIT | (__X32_SYSCALL_BASE + n))


#define __NR_read				__NR_COMMON_SYSCALL(0)
#define __NR_write				__NR_COMMON_SYSCALL(1)
#define __NR_open				__NR_COMMON_SYSCALL(2)
#define __NR_close				__NR_COMMON_SYSCALL(3)
#define __NR_stat				__NR_COMMON_SYSCALL(4)
#define __NR_fstat				__NR_COMMON_SYSCALL(5)
#define __NR_lstat				__NR_COMMON_SYSCALL(6)
#define __NR_poll				__NR_COMMON_SYSCALL(7)

#define __NR_lseek				__NR_COMMON_SYSCALL(8)
#define __NR_mmap				__NR_COMMON_SYSCALL(9)
#define __NR_mprotect				__NR_COMMON_SYSCALL(10)
#define __NR_munmap				__NR_COMMON_SYSCALL(11)
#define __NR_brk				__NR_COMMON_SYSCALL(12)
#define __NR_rt_sigprocmask			__NR_COMMON_SYSCALL(14)

#define __NR_pread64				__NR_COMMON_SYSCALL(17)
#define __NR_pwrite64				__NR_COMMON_SYSCALL(18)
#define __NR_access				__NR_COMMON_SYSCALL(21)
#define __NR_pipe				__NR_COMMON_SYSCALL(22)
#define __NR_select				__NR_COMMON_SYSCALL(23)

#define __NR_sched_yield			__NR_COMMON_SYSCALL(24)
#define __NR_mremap				__NR_COMMON_SYSCALL(25)
#define __NR_msync				__NR_COMMON_SYSCALL(26)
#define __NR_mincore				__NR_COMMON_SYSCALL(27)
#define __NR_madvise				__NR_COMMON_SYSCALL(28)
#define __NR_shmget				__NR_COMMON_SYSCALL(29)
#define __NR_shmat				__NR_COMMON_SYSCALL(30)
#define __NR_shmctl				__NR_COMMON_SYSCALL(31)

#define __NR_dup				__NR_COMMON_SYSCALL(32)
#define __NR_dup2				__NR_COMMON_SYSCALL(33)
#define __NR_pause				__NR_COMMON_SYSCALL(34)
#define __NR_nanosleep				__NR_COMMON_SYSCALL(35)
#define __NR_getitimer				__NR_COMMON_SYSCALL(36)
#define __NR_alarm				__NR_COMMON_SYSCALL(37)
#define __NR_setitimer				__NR_COMMON_SYSCALL(38)
#define __NR_getpid				__NR_COMMON_SYSCALL(39)

#define __NR_sendfile				__NR_COMMON_SYSCALL(40)
#define __NR_socket				__NR_COMMON_SYSCALL(41)
#define __NR_connect				__NR_COMMON_SYSCALL(42)
#define __NR_accept				__NR_COMMON_SYSCALL(43)
#define __NR_sendto				__NR_COMMON_SYSCALL(44)

#define __NR_shutdown				__NR_COMMON_SYSCALL(48)
#define __NR_bind				__NR_COMMON_SYSCALL(49)
#define __NR_listen				__NR_COMMON_SYSCALL(50)
#define __NR_getsockname			__NR_COMMON_SYSCALL(51)
#define __NR_getpeername			__NR_COMMON_SYSCALL(52)
#define __NR_socketpair				__NR_COMMON_SYSCALL(53)
#define __NR_setsockopt				__NR_COMMON_SYSCALL(54)
#define __NR_getsockopt				__NR_COMMON_SYSCALL(55)

#define __NR_clone				__NR_COMMON_SYSCALL(56)
#define __NR_fork				__NR_COMMON_SYSCALL(57)
#define __NR_vfork				__NR_COMMON_SYSCALL(58)
#define __NR_exit				__NR_COMMON_SYSCALL(60)
#define __NR_wait4				__NR_COMMON_SYSCALL(61)
#define __NR_kill				__NR_COMMON_SYSCALL(62)
#define __NR_uname				__NR_COMMON_SYSCALL(63)

#define __NR_semget				__NR_COMMON_SYSCALL(64)
#define __NR_semop				__NR_COMMON_SYSCALL(65)
#define __NR_semctl				__NR_COMMON_SYSCALL(66)
#define __NR_shmdt				__NR_COMMON_SYSCALL(67)
#define __NR_msgget				__NR_COMMON_SYSCALL(68)
#define __NR_msgsnd				__NR_COMMON_SYSCALL(69)
#define __NR_msgrcv				__NR_COMMON_SYSCALL(70)
#define __NR_msgctl				__NR_COMMON_SYSCALL(71)

#define __NR_fcntl				__NR_COMMON_SYSCALL(72)
#define __NR_flock				__NR_COMMON_SYSCALL(73)
#define __NR_fsync				__NR_COMMON_SYSCALL(74)
#define __NR_fdatasync				__NR_COMMON_SYSCALL(75)
#define __NR_truncate				__NR_COMMON_SYSCALL(76)
#define __NR_ftruncate				__NR_COMMON_SYSCALL(77)
#define __NR_getcwd				__NR_COMMON_SYSCALL(79)

#define __NR_chdir				__NR_COMMON_SYSCALL(80)
#define __NR_fchdir				__NR_COMMON_SYSCALL(81)
#define __NR_rename				__NR_COMMON_SYSCALL(82)
#define __NR_mkdir				__NR_COMMON_SYSCALL(83)
#define __NR_rmdir				__NR_COMMON_SYSCALL(84)
#define __NR_creat				__NR_COMMON_SYSCALL(85)
#define __NR_link				__NR_COMMON_SYSCALL(86)
#define __NR_unlink				__NR_COMMON_SYSCALL(87)

#define __NR_symlink				__NR_COMMON_SYSCALL(88)
#define __NR_readlink				__NR_COMMON_SYSCALL(89)
#define __NR_chmod				__NR_COMMON_SYSCALL(90)
#define __NR_fchmod				__NR_COMMON_SYSCALL(91)
#define __NR_chown				__NR_COMMON_SYSCALL(92)
#define __NR_fchown				__NR_COMMON_SYSCALL(93)
#define __NR_lchown				__NR_COMMON_SYSCALL(94)
#define __NR_umask				__NR_COMMON_SYSCALL(95)

#define __NR_gettimeofday			__NR_COMMON_SYSCALL(96)
#define __NR_getrlimit				__NR_COMMON_SYSCALL(97)
#define __NR_getrusage				__NR_COMMON_SYSCALL(98)
#define __NR_sysinfo				__NR_COMMON_SYSCALL(99)
#define __NR_ptrace				__NR_COMMON_SYSCALL(101)
#define __NR_getuid				__NR_COMMON_SYSCALL(102)
#define __NR_syslog				__NR_COMMON_SYSCALL(103)

#define __NR_getgid				__NR_COMMON_SYSCALL(104)
#define __NR_setuid				__NR_COMMON_SYSCALL(105)
#define __NR_setgid				__NR_COMMON_SYSCALL(106)
#define __NR_geteuid				__NR_COMMON_SYSCALL(107)
#define __NR_getegid				__NR_COMMON_SYSCALL(108)
#define __NR_setpgid				__NR_COMMON_SYSCALL(109)
#define __NR_getppid				__NR_COMMON_SYSCALL(110)
#define __NR_getpgrp				__NR_COMMON_SYSCALL(111)

#define __NR_setsid				__NR_COMMON_SYSCALL(112)
#define __NR_setreuid				__NR_COMMON_SYSCALL(113)
#define __NR_setregid				__NR_COMMON_SYSCALL(114)
#define __NR_getgroups				__NR_COMMON_SYSCALL(115)
#define __NR_setgroups				__NR_COMMON_SYSCALL(116)
#define __NR_setresuid				__NR_COMMON_SYSCALL(117)
#define __NR_getresuid				__NR_COMMON_SYSCALL(118)
#define __NR_setresgid				__NR_COMMON_SYSCALL(119)

#define __NR_getresgid				__NR_COMMON_SYSCALL(120)
#define __NR_getpgid				__NR_COMMON_SYSCALL(121)
#define __NR_setfsuid				__NR_COMMON_SYSCALL(122)
#define __NR_setfsgid				__NR_COMMON_SYSCALL(123)
#define __NR_getsid				__NR_COMMON_SYSCALL(124)
#define __NR_capget				__NR_COMMON_SYSCALL(125)
#define __NR_capset				__NR_COMMON_SYSCALL(126)

#define __NR_rt_sigsuspend			__NR_COMMON_SYSCALL(130)
#define __NR_utime				__NR_COMMON_SYSCALL(132)
#define __NR_mknod				__NR_COMMON_SYSCALL(133)

#define __NR_personality			__NR_COMMON_SYSCALL(135)

#define __NR_ustat				__NR_COMMON_SYSCALL(136)
#define __NR_statfs				__NR_COMMON_SYSCALL(137)
#define __NR_fstatfs				__NR_COMMON_SYSCALL(138)
#define __NR_sysfs				__NR_COMMON_SYSCALL(139)

#define __NR_getpriority			__NR_COMMON_SYSCALL(140)
#define __NR_setpriority			__NR_COMMON_SYSCALL(141)
#define __NR_sched_setparam			__NR_COMMON_SYSCALL(142)
#define __NR_sched_getparam			__NR_COMMON_SYSCALL(143)
#define __NR_sched_setscheduler			__NR_COMMON_SYSCALL(144)
#define __NR_sched_getscheduler			__NR_COMMON_SYSCALL(145)
#define __NR_sched_get_priority_max		__NR_COMMON_SYSCALL(146)
#define __NR_sched_get_priority_min		__NR_COMMON_SYSCALL(147)
#define __NR_sched_rr_get_interval		__NR_COMMON_SYSCALL(148)

#define __NR_mlock				__NR_COMMON_SYSCALL(149)
#define __NR_munlock				__NR_COMMON_SYSCALL(150)
#define __NR_mlockall				__NR_COMMON_SYSCALL(151)
#define __NR_munlockall				__NR_COMMON_SYSCALL(152)

#define __NR_vhangup				__NR_COMMON_SYSCALL(153)

#define __NR_modify_ldt				__NR_COMMON_SYSCALL(154)

#define __NR_pivot_root				__NR_COMMON_SYSCALL(155)


#define __NR_prctl				__NR_COMMON_SYSCALL(157)
#define __NR_arch_prctl				__NR_COMMON_SYSCALL(158)

#define __NR_adjtimex				__NR_COMMON_SYSCALL(159)

#define __NR_setrlimit				__NR_COMMON_SYSCALL(160)

#define __NR_chroot				__NR_COMMON_SYSCALL(161)

#define __NR_sync				__NR_COMMON_SYSCALL(162)

#define __NR_acct				__NR_COMMON_SYSCALL(163)

#define __NR_settimeofday			__NR_COMMON_SYSCALL(164)

#define __NR_mount				__NR_COMMON_SYSCALL(165)
#define __NR_umount2				__NR_COMMON_SYSCALL(166)

#define __NR_swapon				__NR_COMMON_SYSCALL(167)
#define __NR_swapoff				__NR_COMMON_SYSCALL(168)

#define __NR_reboot				__NR_COMMON_SYSCALL(169)

#define __NR_sethostname			__NR_COMMON_SYSCALL(170)
#define __NR_setdomainname			__NR_COMMON_SYSCALL(171)

#define __NR_iopl				__NR_COMMON_SYSCALL(172)
#define __NR_ioperm				__NR_COMMON_SYSCALL(173)

#define __NR_init_module			__NR_COMMON_SYSCALL(175)
#define __NR_delete_module			__NR_COMMON_SYSCALL(176)

#define __NR_quotactl				__NR_COMMON_SYSCALL(179)


#define __NR_getpmsg				__NR_COMMON_SYSCALL(181)
#define __NR_putpmsg				__NR_COMMON_SYSCALL(182)

#define __NR_afs_syscall			__NR_COMMON_SYSCALL(183)

#define __NR_tuxcall				__NR_COMMON_SYSCALL(184)

#define __NR_security				__NR_COMMON_SYSCALL(185)

#define __NR_gettid				__NR_COMMON_SYSCALL(186)

#define __NR_readahead				__NR_COMMON_SYSCALL(187)
#define __NR_setxattr				__NR_COMMON_SYSCALL(188)
#define __NR_lsetxattr				__NR_COMMON_SYSCALL(189)
#define __NR_fsetxattr				__NR_COMMON_SYSCALL(190)
#define __NR_getxattr				__NR_COMMON_SYSCALL(191)
#define __NR_lgetxattr				__NR_COMMON_SYSCALL(192)
#define __NR_fgetxattr				__NR_COMMON_SYSCALL(193)
#define __NR_listxattr				__NR_COMMON_SYSCALL(194)
#define __NR_llistxattr				__NR_COMMON_SYSCALL(195)
#define __NR_flistxattr				__NR_COMMON_SYSCALL(196)
#define __NR_removexattr			__NR_COMMON_SYSCALL(197)
#define __NR_lremovexattr			__NR_COMMON_SYSCALL(198)
#define __NR_fremovexattr			__NR_COMMON_SYSCALL(199)
#define __NR_tkill				__NR_COMMON_SYSCALL(200)
#define __NR_time				__NR_COMMON_SYSCALL(201)
#define __NR_futex				__NR_COMMON_SYSCALL(202)
#define __NR_sched_setaffinity			__NR_COMMON_SYSCALL(203)
#define __NR_sched_getaffinity			__NR_COMMON_SYSCALL(204)
#define __NR_io_setup				__NR_COMMON_SYSCALL(206)
#define __NR_io_destroy				__NR_COMMON_SYSCALL(207)
#define __NR_io_getevents			__NR_COMMON_SYSCALL(208)
#define __NR_io_submit				__NR_COMMON_SYSCALL(209)
#define __NR_io_cancel				__NR_COMMON_SYSCALL(210)
#define __NR_lookup_dcookie			__NR_COMMON_SYSCALL(212)
#define __NR_epoll_create			__NR_COMMON_SYSCALL(213)
#define __NR_remap_file_pages			__NR_COMMON_SYSCALL(216)
#define __NR_getdents64				__NR_COMMON_SYSCALL(217)
#define __NR_set_tid_address			__NR_COMMON_SYSCALL(218)
#define __NR_restart_syscall			__NR_COMMON_SYSCALL(219)
#define __NR_semtimedop				__NR_COMMON_SYSCALL(220)
#define __NR_fadvise64				__NR_COMMON_SYSCALL(221)
#define __NR_timer_settime			__NR_COMMON_SYSCALL(223)
#define __NR_timer_gettime			__NR_COMMON_SYSCALL(224)
#define __NR_timer_getoverrun			__NR_COMMON_SYSCALL(225)
#define __NR_timer_delete			__NR_COMMON_SYSCALL(226)
#define __NR_clock_settime			__NR_COMMON_SYSCALL(227)
#define __NR_clock_gettime			__NR_COMMON_SYSCALL(228)
#define __NR_clock_getres			__NR_COMMON_SYSCALL(229)
#define __NR_clock_nanosleep			__NR_COMMON_SYSCALL(230)
#define __NR_exit_group				__NR_COMMON_SYSCALL(231)
#define __NR_epoll_wait				__NR_COMMON_SYSCALL(232)
#define __NR_epoll_ctl				__NR_COMMON_SYSCALL(233)
#define __NR_tgkill				__NR_COMMON_SYSCALL(234)
#define __NR_utimes				__NR_COMMON_SYSCALL(235)
#define __NR_mbind				__NR_COMMON_SYSCALL(237)
#define __NR_set_mempolicy			__NR_COMMON_SYSCALL(238)
#define __NR_get_mempolicy			__NR_COMMON_SYSCALL(239)
#define __NR_mq_open				__NR_COMMON_SYSCALL(240)
#define __NR_mq_unlink				__NR_COMMON_SYSCALL(241)
#define __NR_mq_timedsend			__NR_COMMON_SYSCALL(242)
#define __NR_mq_timedreceive			__NR_COMMON_SYSCALL(243)
#define __NR_mq_getsetattr			__NR_COMMON_SYSCALL(245)
#define __NR_add_key				__NR_COMMON_SYSCALL(248)
#define __NR_request_key			__NR_COMMON_SYSCALL(249)
#define __NR_keyctl				__NR_COMMON_SYSCALL(250)
#define __NR_ioprio_set				__NR_COMMON_SYSCALL(251)
#define __NR_ioprio_get				__NR_COMMON_SYSCALL(252)
#define __NR_inotify_init			__NR_COMMON_SYSCALL(253)
#define __NR_inotify_add_watch			__NR_COMMON_SYSCALL(254)
#define __NR_inotify_rm_watch			__NR_COMMON_SYSCALL(255)
#define __NR_migrate_pages			__NR_COMMON_SYSCALL(256)
#define __NR_openat				__NR_COMMON_SYSCALL(257)
#define __NR_mkdirat				__NR_COMMON_SYSCALL(258)
#define __NR_mknodat				__NR_COMMON_SYSCALL(259)
#define __NR_fchownat				__NR_COMMON_SYSCALL(260)
#define __NR_futimesat				__NR_COMMON_SYSCALL(261)
#define __NR_newfstatat				__NR_COMMON_SYSCALL(262)
#define __NR_unlinkat				__NR_COMMON_SYSCALL(263)
#define __NR_renameat				__NR_COMMON_SYSCALL(264)
#define __NR_linkat				__NR_COMMON_SYSCALL(265)
#define __NR_symlinkat				__NR_COMMON_SYSCALL(266)
#define __NR_readlinkat				__NR_COMMON_SYSCALL(267)
#define __NR_fchmodat				__NR_COMMON_SYSCALL(268)
#define __NR_faccessat				__NR_COMMON_SYSCALL(269)
#define __NR_pselect6				__NR_COMMON_SYSCALL(270)
#define __NR_ppoll				__NR_COMMON_SYSCALL(271)
#define __NR_unshare				__NR_COMMON_SYSCALL(272)
#define __NR_splice				__NR_COMMON_SYSCALL(275)
#define __NR_tee				__NR_COMMON_SYSCALL(276)
#define __NR_sync_file_range			__NR_COMMON_SYSCALL(277)
#define __NR_utimensat				__NR_COMMON_SYSCALL(280)
#define __NR_epoll_pwait			__NR_COMMON_SYSCALL(281)
#define __NR_signalfd				__NR_COMMON_SYSCALL(282)
#define __NR_timerfd_create			__NR_COMMON_SYSCALL(283)
#define __NR_eventfd				__NR_COMMON_SYSCALL(284)
#define __NR_fallocate				__NR_COMMON_SYSCALL(285)
#define __NR_timerfd_settime			__NR_COMMON_SYSCALL(286)
#define __NR_timerfd_gettime			__NR_COMMON_SYSCALL(287)
#define __NR_accept4				__NR_COMMON_SYSCALL(288)
#define __NR_signalfd4				__NR_COMMON_SYSCALL(289)
#define __NR_eventfd2				__NR_COMMON_SYSCALL(290)
#define __NR_epoll_create1			__NR_COMMON_SYSCALL(291)
#define __NR_dup3				__NR_COMMON_SYSCALL(292)
#define __NR_pipe2				__NR_COMMON_SYSCALL(293)
#define __NR_inotify_init1			__NR_COMMON_SYSCALL(294)
#define __NR_perf_event_open			__NR_COMMON_SYSCALL(298)
#define __NR_fanotify_init			__NR_COMMON_SYSCALL(300)
#define __NR_fanotify_mark			__NR_COMMON_SYSCALL(301)
#define __NR_prlimit64				__NR_COMMON_SYSCALL(302)
#define __NR_name_to_handle_at			__NR_COMMON_SYSCALL(303)
#define __NR_open_by_handle_at			__NR_COMMON_SYSCALL(304)
#define __NR_clock_adjtime			__NR_COMMON_SYSCALL(305)
#define __NR_syncfs                             __NR_COMMON_SYSCALL(306)
#define __NR_setns				__NR_COMMON_SYSCALL(308)
#define __NR_getcpu				__NR_COMMON_SYSCALL(309)

#define __NR_rt_sigaction			__NR_X32_SYSCALL(0)
#define __NR_rt_sigreturn			__NR_X32_SYSCALL(1)
#define __NR_ioctl				__NR_X32_SYSCALL(2)
#define __NR_readv				__NR_X32_SYSCALL(3)
#define __NR_writev				__NR_X32_SYSCALL(4)
#define __NR_recvfrom			__NR_X32_SYSCALL(5)
#define __NR_sendmsg			__NR_X32_SYSCALL(6)
#define __NR_recvmsg			__NR_X32_SYSCALL(7)

#define __NR_execve				__NR_X32_SYSCALL(8)
#define __NR_times				__NR_X32_SYSCALL(9)
#define __NR_rt_sigpending			__NR_X32_SYSCALL(10)
#define __NR_rt_sigtimedwait		__NR_X32_SYSCALL(11)
#define __NR_rt_sigqueueinfo		__NR_X32_SYSCALL(12)
#define __NR_sigaltstack			__NR_X32_SYSCALL(13)
#define __NR_timer_create			__NR_X32_SYSCALL(14)
#define __NR_mq_notify			__NR_X32_SYSCALL(15)

#define __NR_kexec_load			__NR_X32_SYSCALL(16)
#define __NR_waitid				__NR_X32_SYSCALL(17)
#define __NR_set_robust_list		__NR_X32_SYSCALL(18)
#define __NR_get_robust_list		__NR_X32_SYSCALL(19)
#define __NR_vmsplice			__NR_X32_SYSCALL(20)
#define __NR_move_pages			__NR_X32_SYSCALL(21)
#define __NR_preadv				__NR_X32_SYSCALL(22)
#define __NR_pwritev			__NR_X32_SYSCALL(23)

#define __NR_rt_tgsigqueueinfo		__NR_X32_SYSCALL(24)
#define __NR_recvmmsg			__NR_X32_SYSCALL(25)
#define __NR_sendmmsg			__NR_X32_SYSCALL(26)

#endif
